### ISSUE TITLE
Does not compile on 3.18.2+

### ISSUE THREAD

**Issue by fryfrog** [barneyman/somagic#1]
``` console
fryfrog@pi ~/linux $ make M=drivers/media/usb/smi2021 modules
  CC [M]  drivers/media/usb/smi2021/smi2021_main.o
In file included from drivers/media/usb/smi2021/smi2021.h:38:0,
                 from drivers/media/usb/smi2021/smi2021_main.c:31:
drivers/media/usb/smi2021/smi2021_main.c: In function ‘smi2021_usb_probe’:
include/media/v4l2-device.h:141:46: error: ‘const struct v4l2_subdev_core_ops’ has no member named ‘s_std’
    if ((cond) && (sd)->ops->o && (sd)->ops->o->f) \
                                              ^
include/media/v4l2-device.h:184:3: note: in expansion of macro ‘__v4l2_device_call_subdevs_p’
   __v4l2_device_call_subdevs_p(v4l2_dev, __sd,  \
   ^
drivers/media/usb/smi2021/smi2021_main.c:1348:2: note: in expansion of macro ‘v4l2_device_call_all’
  v4l2_device_call_all(&smi2021->v4l2_dev, 0, core, s_std,
  ^
include/media/v4l2-device.h:142:17: error: ‘const struct v4l2_subdev_core_ops’ has no member named ‘s_std’
     (sd)->ops->o->f((sd) , ##args);  \
                 ^
include/media/v4l2-device.h:184:3: note: in expansion of macro ‘__v4l2_device_call_subdevs_p’
   __v4l2_device_call_subdevs_p(v4l2_dev, __sd,  \
   ^
drivers/media/usb/smi2021/smi2021_main.c:1348:2: note: in expansion of macro ‘v4l2_device_call_all’
  v4l2_device_call_all(&smi2021->v4l2_dev, 0, core, s_std,
  ^
scripts/Makefile.build:257: recipe for target 'drivers/media/usb/smi2021/smi2021_main.o' failed
make[1]: *** [drivers/media/usb/smi2021/smi2021_main.o] Error 1
Makefile:1381: recipe for target '_module_drivers/media/usb/smi2021' failed
make: *** [_module_drivers/media/usb/smi2021] Error 2
```

``` console
fryfrog@pi ~/linux $ gcc --version
gcc (Raspbian 4.8.3-13) 4.8.3

fryfrog@pi ~/linux $ g++ --version
g++ (Raspbian 4.8.3-13) 4.8.3

fryfrog@pi ~/linux $ cat /proc/version
Linux version 3.18.2+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #736 PREEMPT Mon Jan 12 22:03:33 GMT 2015
```

**Comment by barneyman** [comment]
i'll have a look

**Comment by barneyman** [comment]
compiles now for 3.18.5
